export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE"

//===========SORTING============================
export const SORTING_REQUEST="SORTING_REQUEST";
export const SORTING_SUCCESS="SORTING_SUCCESS";
export const SORTING_FAILURE="SORTING_FAILURE";